server:
  port: ${port:9000}

service:
    name: Credit Card Service

springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  show-actuator: false
  writer-with-default-pretty-printer: true

spring:
  datasource:
    url: jdbc:h2:mem:ccdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
